owner: intakefoods
repo: status.intakefoods.kr
user-agent: intakefoods
sites:
  - name: Shopintake
    url: https://www.shopintake.com
  - name: FoodB2B
    url: https://www.foodb2b.kr
  - name: Intakefoods
    url: https://www.intakefoods.kr
notifications:
  - type: slack
    channel: C016QTU9S9Y
assignees:
  - youngilcho
status-website:
  cname: status.intakefoods.kr
  logoUrl: https://www.shopintake.com/static/intake/img/common/favicon.ico
  name: status.intakefoods
  introTitle: "**status.intakefoods** is uptime monitor and status page for INTAKE Co., Ltd., powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
